# action.yml
name: 'cfml build tools'
inputs:
  cfcompile-args:
    required: true  
  fixinator-args:
    required: true
  fixinator-key:
    required: true
outputs:
  time: # id of output
    description: 'The time this ran'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cfcompile-args }}
    - ${{ inputs.fixinator-args }}
    - ${{ inputs.fixinator-key }}

