on:
  push:
    branches: [ main ]

jobs:
  hello_world_job_private:
    runs-on: ubuntu-latest
    name: test task private run
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: CFML Build Tools
        id: cfml_build_tools
        uses: ./ # Uses an action in the root directory
        with:
          cfcompile-args: 'sourcePath=./tests destPath=./tests/compiled cfengine=lucee@5.3.7.47'

      - name: Check Result
        run: |
          ls -al
          (test -d ${{ github.workspace }}/tests/compiled) || (echo "Missing compiled dir" && exit 1)

      - name: Get the output time
        run: echo "The time was ${{ steps.cfml_build_tools.outputs.time }}"

